### PR TITLE
Add license

### PR DESCRIPTION
**Pull request by hfattahi**
Adding license as instructed by Caltech/JPL open source agreement.

### CODE REVIEW

**Comment by gmgunter** [comment]
I see, thanks. All of the other opera-adt repos have a `LICENSE` file with the Apache-2.0 license text, so I just grabbed that without looking closely at the READMEs.

I'm a bit confused about this, actually. This new license text appears to be a [3-Clause BSD license](https://opensource.org/licenses/BSD-3-Clause). How are these projects licensed under \*both\* this BSD-3-Clause license \*and\* the Apache-2.0 license? The terms of each license are somewhat different. Would downstream projects need to meet the conditions of both licenses, or can they choose which license to follow?

It seems to me that it's probably best to just use a single license to keep things simple and prevent confusion. Would it be alright if I just replace the old `LICENSE` file with this new text?

**Comment by hfattahi** [comment]
Good point @gmgunter. In the open source agreement the above text has been suggested as a markup to use and very clearly Apache version 2.0 is stated as the approved license. Let's discuss offline and look at the agreement together before deciding on this PR.

**Comment by hfattahi** [comment]
Good point @gmgunter. In the open source agreement the above text has been suggested as a markup to use and very clearly Apache version 2.0 is stated as the approved license. Let's discuss offline and look at the agreement together before deciding on this PR.

**Comment by gmgunter** [comment]
So @hfattahi and I reached out to the JPL SRA yesterday for clarification. The gist of their response was:

* They recommend that we include the text of both licenses (i.e. both the Caltech/JPL Markup Language \*and\* the
Apache-2.0 license text) in our open source repositories
* Downstream users/recipients may choose either license at their discretion

I've seen a small number of projects with a similar license structure that might be useful as reference for us, e.g.

* https://github.com/spack/spack#license
* https://github.com/ned14/llfio/blob/develop/Licence.txt

@hfattahi I made an attempt at addressing this in d6f1789. Will you take a look when you get a chance and let me know what you think of this approach?

**Comment by hfattahi** [comment]
Thanks @gmgunter. Yes your commit addressed all I wanted to include in this PR. Therefore this PR is no longer needed. I will close with this comment.

**Pull request closed without merging**
